//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.IOBroker.Service {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceSettings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HA.IOBroker.Service.ResourceSettings", typeof(ResourceSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;DeviceGroups&quot;: [
        ///    {
        ///      &quot;GroupName&quot;: &quot;HM_Window_Sensor&quot;,
        ///      &quot;Properties&quot;: {
        ///        &quot;1.LOWBAT&quot;: {
        ///          &quot;PropertyName&quot;: &quot;LowBattery&quot;,
        ///          &quot;Historize&quot;: true,
        ///          &quot;DataType&quot;: &quot;Boolean&quot;
        ///        },
        ///        &quot;1.STATE&quot;: {
        ///          &quot;PropertyName&quot;: &quot;WindowOpen&quot;,
        ///          &quot;Historize&quot;: true,
        ///          &quot;DataType&quot;: &quot;Boolean&quot;
        ///        }
        ///      }
        ///    },
        ///    {
        ///      &quot;GroupName&quot;: &quot;HM_Heating&quot;,
        ///      &quot;Properties&quot;: {
        ///        &quot;1.LOWBAT&quot;: {
        ///          &quot;PropertyName&quot;: &quot;LowBattery&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string devices {
            get {
                return ResourceManager.GetString("devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;redis&quot;: {
        ///    &quot;host&quot;: &quot;192.168.111.50&quot;,
        ///    &quot;port&quot;: 6379
        ///  },
        ///  &quot;influxDB&quot;: {
        ///    &quot;url&quot;: &quot;http://192.168.111.237:8086/&quot;,
        ///    &quot;org&quot;: &quot;ORG&quot;,
        ///    &quot;bucket&quot;: &quot;BUCKET&quot;,
        ///    &quot;token&quot;: &quot;&quot;
        ///  }
        ///}.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
    }
}
